import peers.views.home
import peers.views.create_question
import peers.views.question
import peers.views.students.lookup
import peers.views.students.answer
import peers.views.question_fetch
import peers.views.admin.list
import peers.views.admin.delete
import peers.views.admin.edit
import peers.views.admin.reset
import peers.views.images
import peers.views.admin.openclose
import peers.views.admin.export
import peers.views.static
import peers.views.login.login
import peers.views.login.logout
import peers.views.admin.create_group
import peers.views.admin.orders
import peers.views.login.register
